-- 1. ADD MISSING COLUMNS TO RESOURCE UNITS
ALTER TABLE resource_units 
ADD COLUMN IF NOT EXISTS base_price DECIMAL(10, 2) DEFAULT 0.00;

-- 2. ADD MISSING COLUMNS TO BOOKINGS
ALTER TABLE bookings 
ADD COLUMN IF NOT EXISTS guest_name TEXT,
ADD COLUMN IF NOT EXISTS guest_phone TEXT,
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS payment_status TEXT DEFAULT 'unpaid',
ADD COLUMN IF NOT EXISTS payment_method TEXT,
ADD COLUMN IF NOT EXISTS paid_amount DECIMAL(10, 2) DEFAULT 0.00,
ADD COLUMN IF NOT EXISTS bill_items JSONB DEFAULT '[]'::jsonb;

-- 3. ADD PRODUCTS CATEGORY IF MISSING
ALTER TABLE products 
ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'drink';


